In [2]:
# coding: utf-8

"""로컬상에서 현재 폴더에 날짜_Sample info.xlsx (ex] 200214_Sample info.xlsx)가 존재할때 해당 py를 실행시키고
다섯글자 id와 날짜를 입력하면 sample_sheet2를 만들어주는 프로그램입니다."""
import sys
import pandas as pd
import numpy as np
from collections import Counter
date = '200330'
Run_id = 'HTEST'

In [3]:
def check_duple(df):
    sample_num = 0
    if len(df['Sample']) == len(df['Sample'].unique()): # Sample 이름 중복 확인
        sample_num = len(df['Sample'])
    else:
        print("Sample name 중복")
        for sname,cnt in Counter(df['Sample']):
            if cnt != 1:
                print(sname,cnt)

    index_df=df.iloc[:,10:14]
    idx_arr = index_df.values.flatten()
    unique,v = np.unique(idx_arr,return_counts=True)
    idx_dict = dict(zip(unique,v))
    index_duple = 0
    if sum(idx_dict.values()) != len(idx_dict):
        duple_li = [k for k,v in idx_dict.items() if v!=1]
        if len(duple_li) == 1 and duple_li[0] == '---':
            print("Single Index Sample!!")
            print(*list(df[index_df['Unnamed: 11']=='---'].Sample),sep='\n')
            index_duple = 1
        else:
            print("Index 중복")
            for idx_pair,cnt in Counter(idx_arr).items():
                if cnt != 1:
                    print(idx_pair,cnt)
    else:
        index_duple = 1
    return sample_num,index_duple,index_df

def make_sam_sheet(df,sample_num,index_df,name,date):
    report_header=['specimen_ID', 'specimen_type', 'doctor', 'hospital', 'department', 'address', 'patient ID',
               'patient', 'cancer', 'site', 'collected', 'received', 'reported']
    report_value=['AL colon', 'cfDNA', 'Dr. Moon', 'IMBDx', 'Analysis', 'BYC building', '-', '-',
              'Colon cancer', 'blood', '2019-07-01', '2019-07-10', '2019-07-12']
    report_df = pd.DataFrame([report_value for i in range(sample_num)])
    index_header = [ "index_t"+str(num) for num in range(1,5)]
    df_header = "sample", *index_header , *report_header
    sampleSheet = pd.concat([df['Sample'],index_df,report_df],axis=1)
    sampleSheet.columns=df_header
    sampleSheet[['index_t1', 'index_t2', 'index_t3', 'index_t4']] = sampleSheet[['index_t1', 'index_t2', 'index_t3', 'index_t4']].replace('---','-')
    sampleSheet.to_excel(date+"_"+name+"_"+"samplesheet.xlsx",index=False)
    return sampleSheet

def addIndexPair(df):
    for num in range(1,5):
        F_li = df[f"Index{num}F"].tolist()
        R_li = df[f"Index{num}R"].tolist()
        df[f"Index{num}F-R"]=[str(F)+"-"+str(R) for F,R in zip(F_li,R_li)]
    return df

def CheckIndexPair(df):
    for lane in range(1,5):
        if (df[f"Unnamed: {lane+9}"] == df[f"Index{lane}F-R"]).sum()==len(df):
            print(f"{lane} lane is same. Good!!")
        else:
            print(f"{lane} is not same!!. Need confirmation!!")
            raise Exception("Index Pair Not Same. Check Index Pair. cwj")

df = pd.read_excel(date+'_Sample info.xlsx')
df = addIndexPair(df)
CheckIndexPair(df)
sample_num,index_duple,index_df = check_duple(df)

if sample_num*index_duple : # 둘중 하나라도 0이면 안됨
    sampleSheet = make_sam_sheet(df,sample_num,index_df,Run_id,date)
else:
    print("중복 확인 요망")
    raise Exception("Sample Name or Index-pair duplicated. Check ")

# #엑셀에서 바로 가져오기 -> split("	")
# report_header="""specimen_ID	specimen_type	doctor	hospital	department	address	patient ID	patient	cancer	site	collected	received	reported""".split('	')
# report_value="""AL colon	cfDNA	Dr. Moon	IMBDx	Analysis	BYC building	-	-	Colon cancer	blood	2019-07-01	2019-07-10	2019-07-12""".split('	')

1 lane is same. Good!!
2 lane is same. Good!!
3 lane is same. Good!!
4 lane is same. Good!!
Single Index Sample!!
LAH194
LAH195
LAH196
LAH197
LAH198
LAH199
LAH200
LAH201
LAH202
LAH203
LAH204
LAH205
LAH206
LAH207
LAH208
LAH209

In [9]:
# print(*list(df[index_df['Unnamed: 11']=='---'].Sample),sep='\n')

In [55]:
sample_num = 0
if len(df['Sample']) == len(df['Sample'].unique()): # Sample 이름 중복 확인
    sample_num = len(df['Sample'])
else:
    print("Sample name 중복")
    for sname,cnt in Counter(df['Sample']):
        if cnt != 1:
            print(sname,cnt)

index_df=df.iloc[:,10:14]
idx_arr = index_df.values.flatten()
unique,v = np.unique(idx_arr,return_counts=True)
idx_dict = dict(zip(unique,v))
index_duple = 0
if sum(idx_dict.values()) != len(idx_dict):
    duple_li = [k for k,v in idx_dict.items() if v!=1]
    if len(duple_li) == 1 and duple_li[0] == '---':
        print("Single Index Sample!!")
        print(*list(df[index_df['Unnamed: 11']=='---'].Sample),sep='\n')
    else:
        print("Index 중복")
        for idx_pair,cnt in Counter(idx_arr).items():
            if cnt != 1:
                print(idx_pair,cnt)

Single Index Sample!!
LAH115
LAH116
LAH117
LAH118
LAH119
LAH122
LAH123
LAH124
LAH125
LAH126

In [7]:
sampleSheet.iloc[:,1:].head()

,index_t1,index_t2,index_t3,index_t4,specimen_ID,specimen_type,doctor,hospital,department,address,patient ID,patient,cancer,site,collected,received,reported
0,501-705,-,-,-,AL colon,cfDNA,Dr. Moon,IMBDx,Analysis,BYC building,-,-,Colon cancer,blood,2019-07-01,2019-07-10,2019-07-12
1,501-706,-,-,-,AL colon,cfDNA,Dr. Moon,IMBDx,Analysis,BYC building,-,-,Colon cancer,blood,2019-07-01,2019-07-10,2019-07-12
2,501-707,-,-,-,AL colon,cfDNA,Dr. Moon,IMBDx,Analysis,BYC building,-,-,Colon cancer,blood,2019-07-01,2019-07-10,2019-07-12
3,501-708,-,-,-,AL colon,cfDNA,Dr. Moon,IMBDx,Analysis,BYC building,-,-,Colon cancer,blood,2019-07-01,2019-07-10,2019-07-12
4,502-705,-,-,-,AL colon,cfDNA,Dr. Moon,IMBDx,Analysis,BYC building,-,-,Colon cancer,blood,2019-07-01,2019-07-10,2019-07-12